<script>var plugin_path = '<?php echo base_url();?>assets/plugins/';</script>
<script src="<?php echo base_url();?>assets/plugins/jquery/jquery-3.4.1.min.js"></script>
<script src="<?php echo base_url();?>assets/js/scripts.js"></script>
<!-- STYLESWITCHER - REMOVE
<script async src="demo_files/styleswitcher/styleswitcher.js"></script> -->
<!-- SWIPER SLIDER -->
<script src="<?php echo base_url();?>assets/plugins/slider.swiper/dist/js/swiper.min.js"></script>
<script src="<?php echo base_url();?>assets/js/view/demo.swiper_slider.js"></script>
<script src="<?php echo base_url();?>assets/amcharts/old/amcharts.js"></script>
<script src="<?php echo base_url();?>assets/amcharts/old/serial.js"></script>
<script src="<?php echo base_url();?>assets/amcharts/old/dark.js"></script>
<script src="<?php echo base_url();?>assets/amcharts/old/export.min.js"></script>
<script src="<?php echo base_url();?>assets/amcharts/old/dataloader.js"></script>
<script src="<?php echo base_url();?>assets/amcharts/core.js"></script>
<script src="<?php echo base_url();?>assets/amcharts/charts.js"></script>
<script src="<?php echo base_url();?>assets/amcharts/themes/dataviz.js"></script>
<script src="<?php echo base_url();?>assets/amcharts/themes/animated.js"></script>
<script src="<?php echo base_url();?>assets/plugins/datatables/js/jquery.dataTables.min.js"></script>
<script src="<?php echo base_url();?>assets/plugins/datatables/js/dataTables.tableTools.min.js"></script>
<script src="<?php echo base_url();?>assets/plugins/datatables/js/dataTables.colReorder.min.js"></script>
<script src="<?php echo base_url();?>assets/plugins/datatables/js/dataTables.scroller.min.js"></script>
<script src="<?php echo base_url();?>assets/plugins/datatables/dataTables.bootstrap.js"></script>
<script src="<?php echo base_url();?>assets/plugins/select2/js/select2.full.min.js"></script>
